package com.example.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Client POJO.
 * @author ivan
 *
 */
@Entity
@Table(name = "clients")
public class Client {

	// An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	private String name;
	private String lastName;
	/**
	 * @return the identifier
	 */
	public long getIdentifier() {
		return id;
	}
	/**
	 * @param identifier the identifier to set
	 */
	public void setIdentifier(long identifier) {
		this.id = identifier;
	}
	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}
	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
	/**
	 * @return the lastName
	 */
	public String getLastName() {
		return lastName;
	}
	/**
	 * @param lastName the lastName to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	
	
}
